package ch8;

public class EceptionEx17 {

	public static void main(String[] args) {
		try {
			method1();
		}catch (Exception e) {
			System.out.println("main메서드에서 예외가 처리되었습니다.");
		}
	}
	
	static void method1() throws Exception{
		try {
			throw new Exception();
		}catch (Exception e) {
			System.out.println("method1()에서 예외가 처리되었습니다.");
			throw e;   //다시 예외 발생시키기
		}
	}

}
